let books = [
  {
    id: 1,
    title: "Le Seigneur des Anneaux",
    category_id: 9,
    number_of_pages: 500,
    year_of_publication: 1954,
    average_ratings: null,
    cover_image: "https://example.com/book1-cover.jpg",
    extract_pdf: "https://example.com/book1-extract.pdf",
    summary: "Un récit épique dans un monde fantastique...",
  },
  {
    id: 2,
    title: "1984",
    category_id: 8,
    number_of_pages: 300,
    year_of_publication: 1949,
    average_ratings: null,
    cover_image: "https://example.com/book2-cover.jpg",
    extract_pdf: "https://example.com/book2-extract.pdf",
    summary: "Une vision sombre de l'avenir...",
  },
  {
    id: 3,
    title: "Orgueil et Préjugés",
    category_id: 6,
    number_of_pages: 400,
    year_of_publication: 1813,
    average_ratings: null,
    cover_image: "https://example.com/book3-cover.jpg",
    extract_pdf: "https://example.com/book3-extract.pdf",
    summary: "Une histoire d'amour classique...",
  },
  {
    id: 4,
    title: "Fondation",
    category_id: 1,
    number_of_pages: 350,
    year_of_publication: 1951,
    average_ratings: null,
    cover_image: "https://example.com/book4-cover.jpg",
    extract_pdf: "https://example.com/book4-extract.pdf",
    summary: "La saga de l'avenir de l'humanité...",
  },
  {
    id: 5,
    title: "Crime et Châtiment",
    category_id: 1,
    number_of_pages: 450,
    year_of_publication: 1866,
    average_ratings: null,
    cover_image: "https://example.com/book5-cover.jpg",
    extract_pdf: "https://example.com/book5-extract.pdf",
    summary: "Un thriller psychologique...",
  },
  {
    id: 6,
    title: "Les Misérables",
    category_id: 12,
    number_of_pages: 1200,
    year_of_publication: 1862,
    average_ratings: null,
    cover_image: "https://example.com/book6-cover.jpg",
    extract_pdf: "https://example.com/book6-extract.pdf",
    summary: "Un récit épique de la vie au XIXe siècle...",
  },
  {
    id: 7,
    title: "Le Petit Prince",
    category_id: 9,
    number_of_pages: 100,
    year_of_publication: 1943,
    average_ratings: null,
    cover_image: "https://example.com/book7-cover.jpg",
    extract_pdf: "https://example.com/book7-extract.pdf",
    summary: "Un conte pour enfants intemporel...",
  },
  {
    id: 8,
    title: "La Ferme des Animaux",
    category_id: 3,
    number_of_pages: 200,
    year_of_publication: 1945,
    average_ratings: null,
    cover_image: "https://example.com/book8-cover.jpg",
    extract_pdf: "https://example.com/book8-extract.pdf",
    summary: "Une allégorie politique...",
  },
  {
    id: 9,
    title: "Le Comte de Monte-Cristo",
    category_id: 7,
    number_of_pages: 900,
    year_of_publication: 1844,
    average_ratings: null,
    cover_image: "https://example.com/book9-cover.jpg",
    extract_pdf: "https://example.com/book9-extract.pdf",
    summary: "Une aventure pleine de revanche...",
  },
  {
    id: 10,
    title: "Cendrillon",
    category_id: 7,
    number_of_pages: 50,
    year_of_publication: 1697,
    average_ratings: null,
    cover_image: "https://example.com/book10-cover.jpg",
    extract_pdf: "https://example.com/book10-extract.pdf",
    summary: "Un conte de fées classique...",
  },
  {
    id: 11,
    title: "Harry Potter à l'école des sorciers",
    category_id: 7,
    number_of_pages: 320,
    year_of_publication: 1997,
    average_ratings: null,
    cover_image: "https://example.com/book11-cover.jpg",
    extract_pdf: "https://example.com/book11-extract.pdf",
    summary: "Le début des aventures du jeune sorcier Harry Potter...",
  },
  {
    id: 12,
    title: "Neuromancien",
    category_id: 7,
    number_of_pages: 270,
    year_of_publication: 1984,
    average_ratings: null,
    cover_image: "https://example.com/book12-cover.jpg",
    extract_pdf: "https://example.com/book12-extract.pdf",
    summary: "Une plongée dans le cyberespace...",
  },
  {
    id: 13,
    title: "Le Nom du Vent",
    category_id: 5,
    number_of_pages: 662,
    year_of_publication: 2007,
    average_ratings: null,
    cover_image: "https://example.com/book13-cover.jpg",
    extract_pdf: "https://example.com/book13-extract.pdf",
    summary: "L'histoire du musicien et magicien Kvothe...",
  },
  {
    id: 14,
    title: "Les Hauts de Hurlevent",
    category_id: 5,
    number_of_pages: 416,
    year_of_publication: 1847,
    average_ratings: null,
    cover_image: "https://example.com/book14-cover.jpg",
    extract_pdf: "https://example.com/book14-extract.pdf",
    summary: "Une histoire de passion et de vengeance...",
  },
  {
    id: 15,
    title: "Le Meilleur des mondes",
    category_id: 2,
    number_of_pages: 288,
    year_of_publication: 1932,
    average_ratings: null,
    cover_image: "https://example.com/book15-cover.jpg",
    extract_pdf: "https://example.com/book15-extract.pdf",
    summary: "Un monde futuriste contrôlé par la technologie...",
  },
  {
    id: 16,
    title: "Le Parrain",
    category_id: 11,
    number_of_pages: 448,
    year_of_publication: 1969,
    average_ratings: null,
    cover_image: "https://example.com/book16-cover.jpg",
    extract_pdf: "https://example.com/book16-extract.pdf",
    summary: "La saga de la famille mafieuse Corleone...",
  },
  {
    id: 17,
    title: "Les Trois Mousquetaires",
    category_id: 10,
    number_of_pages: 704,
    year_of_publication: 1844,
    average_ratings: null,
    cover_image: "https://example.com/book17-cover.jpg",
    extract_pdf: "https://example.com/book17-extract.pdf",
    summary: "Les aventures de d'Artagnan et ses compagnons...",
  },
  {
    id: 18,
    title: "Le Portrait de Dorian Gray",
    category_id: 10,
    number_of_pages: 239,
    year_of_publication: 1890,
    average_ratings: null,
    cover_image: "https://example.com/book18-cover.jpg",
    extract_pdf: "https://example.com/book18-extract.pdf",
    summary: "La décadence d'un homme à travers son portrait...",
  },
  {
    id: 19,
    title: "Le Hobbit",
    category_id: 10,
    number_of_pages: 310,
    year_of_publication: 1937,
    average_ratings: null,
    cover_image: "https://example.com/book19-cover.jpg",
    extract_pdf: "https://example.com/book19-extract.pdf",
    summary: "Le voyage de Bilbo dans la Terre du Milieu...",
  },
  {
    id: 20,
    title: "Le Comte de Monte-Cristo",
    category_id: 2,
    number_of_pages: 900,
    year_of_publication: 1844,
    average_ratings: null,
    cover_image: "https://example.com/book20-cover.jpg",
    extract_pdf: "https://example.com/book20-extract.pdf",
    summary: "Une aventure pleine de revanche...",
  },
  {
    id: 21,
    title: "Les Piliers de la Terre",
    category_id: 3,
    number_of_pages: 973,
    year_of_publication: 1989,
    average_ratings: null,
    cover_image: "https://example.com/book21-cover.jpg",
    extract_pdf: "https://example.com/book21-extract.pdf",
    summary: "Une épopée de construction de cathédrales au Moyen Âge...",
  },
  {
    id: 22,
    title: "Le Vieil Homme et la Mer",
    category_id: 4,
    number_of_pages: 127,
    year_of_publication: 1952,
    average_ratings: null,
    cover_image: "https://example.com/book22-cover.jpg",
    extract_pdf: "https://example.com/book22-extract.pdf",
    summary: "L'histoire d'un vieux pêcheur et d'un énorme poisson...",
  },
  {
    id: 23,
    title: "Le Chardonneret",
    category_id: 5,
    number_of_pages: 864,
    year_of_publication: 2013,
    average_ratings: null,
    cover_image: "https://example.com/book23-cover.jpg",
    extract_pdf: "https://example.com/book23-extract.pdf",
    summary: "La vie tumultueuse d'un jeune homme après un attentat...",
  },
  {
    id: 24,
    title: "Frankenstein",
    category_id: 3,
    number_of_pages: 280,
    year_of_publication: 1818,
    average_ratings: null,
    cover_image: "https://example.com/book24-cover.jpg",
    extract_pdf: "https://example.com/book24-extract.pdf",
    summary:
      "L'histoire du scientifique Victor Frankenstein et de sa créature...",
  },
  {
    id: 25,
    title: "Dracula",
    category_id: 9,
    number_of_pages: 418,
    year_of_publication: 1897,
    average_ratings: null,
    cover_image: "https://example.com/book25-cover.jpg",
    extract_pdf: "https://example.com/book25-extract.pdf",
    summary:
      "L'histoire du comte Dracula et de ses interactions avec la société anglaise...",
  },
  {
    id: 26,
    title: "Les Raisins de la colère",
    category_id: 11,
    number_of_pages: 464,
    year_of_publication: 1939,
    average_ratings: null,
    cover_image: "https://example.com/book26-cover.jpg",
    extract_pdf: "https://example.com/book26-extract.pdf",
    summary: "Les luttes d'une famille pendant la Grande Dépression...",
  },
  {
    id: 27,
    title: "Les Cinq Filles de Mrs Bennet",
    category_id: 4,
    number_of_pages: 400,
    year_of_publication: 1813,
    average_ratings: null,
    cover_image: "https://example.com/book27-cover.jpg",
    extract_pdf: "https://example.com/book27-extract.pdf",
    summary:
      "L'amour et les mariages dans la société anglaise du XIXe siècle...",
  },
  {
    id: 28,
    title: "Le Portrait de Dorian Gray",
    category_id: 8,
    number_of_pages: 239,
    year_of_publication: 1890,
    average_ratings: null,
    cover_image: "https://example.com/book28-cover.jpg",
    extract_pdf: "https://example.com/book28-extract.pdf",
    summary: "La décadence d'un homme à travers son portrait...",
  },
  {
    id: 29,
    title: "Voyage au centre de la Terre",
    category_id: 1,
    number_of_pages: 240,
    year_of_publication: 1864,
    average_ratings: null,
    cover_image: "https://example.com/book29-cover.jpg",
    extract_pdf: "https://example.com/book29-extract.pdf",
    summary: "Une expédition fantastique vers les profondeurs de la Terre...",
  },
  {
    id: 30,
    title: "L'Étranger",
    category_id: 3,
    number_of_pages: 123,
    year_of_publication: 1942,
    average_ratings: null,
    cover_image: "https://example.com/book30-cover.jpg",
    extract_pdf: "https://example.com/book30-extract.pdf",
    summary: "La vie et les actions énigmatiques de Meursault...",
  },
  {
    id: 31,
    title: "Le Silence des Agneaux",
    category_id: 8,
    number_of_pages: 348,
    year_of_publication: 1988,
    average_ratings: null,
    cover_image: "https://example.com/book31-cover.jpg",
    extract_pdf: "https://example.com/book31-extract.pdf",
    summary: "Une traque intense entre un enquêteur et un tueur en série...",
  },
  {
    id: 32,
    title: "Le Guépard",
    category_id: 6,
    number_of_pages: 436,
    year_of_publication: 1958,
    average_ratings: null,
    cover_image: "https://example.com/book32-cover.jpg",
    extract_pdf: "https://example.com/book32-extract.pdf",
    summary:
      "L'histoire d'une famille aristocratique pendant l'unification italienne...",
  },
  {
    id: 33,
    title: "Le Maître et Marguerite",
    category_id: 3,
    number_of_pages: 384,
    year_of_publication: 1967,
    average_ratings: null,
    cover_image: "https://example.com/book33-cover.jpg",
    extract_pdf: "https://example.com/book33-extract.pdf",
    summary: "Un roman fantastique mêlant le diable, l'amour et la satire...",
  },
  {
    id: 34,
    title: "Les Misérables",
    category_id: 6,
    number_of_pages: 1488,
    year_of_publication: 1862,
    average_ratings: null,
    cover_image: "https://example.com/book34-cover.jpg",
    extract_pdf: "https://example.com/book34-extract.pdf",
    summary:
      "L'épopée de Jean Valjean et de la société française du XIXe siècle...",
  },
  {
    id: 35,
    title: "Les Cerfs-volants de Kaboul",
    category_id: 12,
    number_of_pages: 372,
    year_of_publication: 2003,
    average_ratings: null,
    cover_image: "https://example.com/book35-cover.jpg",
    extract_pdf: "https://example.com/book35-extract.pdf",
    summary: "Une histoire d'amitié et de rédemption en Afghanistan...",
  },
  {
    id: 36,
    title: "Le Comte de Monte-Cristo",
    category_id: 1,
    number_of_pages: 900,
    year_of_publication: 1844,
    average_ratings: null,
    cover_image: "https://example.com/book36-cover.jpg",
    extract_pdf: "https://example.com/book36-extract.pdf",
    summary: "Une aventure pleine de revanche...",
  },
  {
    id: 37,
    title: "Dune",
    category_id: 1,
    number_of_pages: 694,
    year_of_publication: 1965,
    average_ratings: null,
    cover_image: "https://example.com/book37-cover.jpg",
    extract_pdf: "https://example.com/book37-extract.pdf",
    summary: "L'épopée interplanétaire dans un futur lointain...",
  },
  {
    id: 38,
    title: "Le Portrait de Dorian Gray",
    category_id: 3,
    number_of_pages: 239,
    year_of_publication: 1890,
    average_ratings: null,
    cover_image: "https://example.com/book38-cover.jpg",
    extract_pdf: "https://example.com/book38-extract.pdf",
    summary: "La décadence d'un homme à travers son portrait...",
  },
  {
    id: 39,
    title: "Le Maître des illusions",
    category_id: 4,
    number_of_pages: 640,
    year_of_publication: 1995,
    average_ratings: null,
    cover_image: "https://example.com/book39-cover.jpg",
    extract_pdf: "https://example.com/book39-extract.pdf",
    summary: "Une aventure magique et mystérieuse...",
  },
  {
    id: 40,
    title: "Le Guerrier Pacifique",
    category_id: 7,
    number_of_pages: 216,
    year_of_publication: 1980,
    average_ratings: null,
    cover_image: "https://example.com/book40-cover.jpg",
    extract_pdf: "https://example.com/book40-extract.pdf",
    summary: "La quête spirituelle d'un homme à travers le monde...",
  },
  {
    id: 41,
    title: "La Stratégie Ender",
    category_id: 11,
    number_of_pages: 324,
    year_of_publication: 1985,
    average_ratings: null,
    cover_image: "https://example.com/book41-cover.jpg",
    extract_pdf: "https://example.com/book41-extract.pdf",
    summary: "L'histoire d'un jeune génie militaire dans un futur spatial...",
  },
  {
    id: 42,
    title: "Le Portrait de Dorian Gray",
    category_id: 9,
    number_of_pages: 239,
    year_of_publication: 1890,
    average_ratings: null,
    cover_image: "https://example.com/book42-cover.jpg",
    extract_pdf: "https://example.com/book42-extract.pdf",
    summary: "La décadence d'un homme à travers son portrait...",
  },
  {
    id: 43,
    title: "Les Fourmis",
    category_id: 5,
    number_of_pages: 320,
    year_of_publication: 1991,
    average_ratings: null,
    cover_image: "https://example.com/book43-cover.jpg",
    extract_pdf: "https://example.com/book43-extract.pdf",
    summary:
      "Un voyage dans le monde des fourmis avec des aspects philosophiques...",
  },
  {
    id: 44,
    title: "Le Comte de Monte-Cristo",
    category_id: 12,
    number_of_pages: 900,
    year_of_publication: 1844,
    average_ratings: null,
    cover_image: "https://example.com/book44-cover.jpg",
    extract_pdf: "https://example.com/book44-extract.pdf",
    summary: "Une aventure pleine de revanche...",
  },
  {
    id: 45,
    title: "Le Meilleur des mondes",
    category_id: 4,
    number_of_pages: 288,
    year_of_publication: 1932,
    average_ratings: null,
    cover_image: "https://example.com/book45-cover.jpg",
    extract_pdf: "https://example.com/book45-extract.pdf",
    summary: "Un monde futuriste contrôlé par la technologie...",
  },
  {
    id: 46,
    title: "La Nuit des temps",
    category_id: 1,
    number_of_pages: 480,
    year_of_publication: 1968,
    average_ratings: null,
    cover_image: "https://example.com/book46-cover.jpg",
    extract_pdf: "https://example.com/book46-extract.pdf",
    summary: "La découverte d'une civilisation ancienne sous la glace...",
  },
  {
    id: 47,
    title: "Les Piliers de la Terre",
    category_id: 10,
    number_of_pages: 973,
    year_of_publication: 1989,
    average_ratings: null,
    cover_image: "https://example.com/book47-cover.jpg",
    extract_pdf: "https://example.com/book47-extract.pdf",
    summary: "Une épopée de construction de cathédrales au Moyen Âge...",
  },
  {
    id: 48,
    title: "La Ferme des Animaux",
    category_id: 7,
    number_of_pages: 200,
    year_of_publication: 1945,
    average_ratings: null,
    cover_image: "https://example.com/book48-cover.jpg",
    extract_pdf: "https://example.com/book48-extract.pdf",
    summary: "Une allégorie politique...",
  },
  {
    id: 49,
    title: "La Marque des anges",
    category_id: 2,
    number_of_pages: 384,
    year_of_publication: 2013,
    average_ratings: null,
    cover_image: "https://example.com/book49-cover.jpg",
    extract_pdf: "https://example.com/book49-extract.pdf",
    summary: "Une enquête mystérieuse liée à des phénomènes surnaturels...",
  },
  {
    id: 50,
    title: "Le Chant des sirènes",
    category_id: 3,
    number_of_pages: 432,
    year_of_publication: 2004,
    average_ratings: null,
    cover_image: "https://example.com/book50-cover.jpg",
    extract_pdf: "https://example.com/book50-extract.pdf",
    summary: "Une aventure fantastique sous les océans...",
  },
];

export { books };
